<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Antelcat.I18N.WPF" Version="2.0.0-preview-1" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resource\Language.ch-zh.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Language.ch-zh.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resource\Language.en-us.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Language.en-us.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resource\Language.ch-zh.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Language.ch-zh.resx</DependentUpon>
      </Compile>
      <Compile Update="Resource\Language.en-us.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Language.en-us.resx</DependentUpon>
      </Compile>
      <Compile Update="Languages\Language.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Language.resx</DependentUpon>
      </Compile>
      <Compile Update="Languages\Language.en-us.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Language.en-us.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

</Project>
